### ISSUE TITLE
Bad flex version check in autogen.sh

### ISSUE THREAD

**Issue by Dan-Fraser** [mrvdb/claws-mail#3]
Trying to build on the Buster alpha release and it says I don't have high enough version of Flex:

```
./autogen.sh 
Flex 2.5.31 or greater is needed to compile Claws Mail git.
```

Yet I have a whole major version newer:
```
$ flex --version
flex 2.6.4
```

The check for version number is naive:
```
if [ $flex_major -lt 2 -o $flex_minor -lt 5 -o $flex_micro -lt 31 ]; then
```

I don't have a suggested fix, I just removed the check from my autogen.sh

**Comment by mrvdb** [comment]
It's probably smarter to report this issue upstream to https://www.thewildbeast.co.uk/claws-mail/bugzilla/index.cgi

The claws mail repository here is just for archiving purposes.
